"""empty message

Revision ID: fcfee2d684c7
Revises: 57305af1bc6e
Create Date: 2023-02-20 15:33:26.544256

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fcfee2d684c7"
down_revision = "57305af1bc6e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_tester", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_tester")
    # ### end Alembic commands ###
