"""empty message

Revision ID: a34d94a2cb31
Revises: 1d2f85735fec
Create Date: 2023-02-16 00:05:10.346429

"""

# revision identifiers, used by Alembic.
revision = "a34d94a2cb31"
down_revision = "1d2f85735fec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
