version: "3"

services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
    - 80:80
    volumes:
    - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    container_name: hackthon-proxy
    networks:
    - backend

  api:
    container_name: hackathon-api
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: hackathon:${HACKATHON_VERSION:-latest}
    restart: always
    env_file:
    - .env
    networks:
    - backend
    expose:
    - 8000
    environment:
      HACKATHON_HOST: 0.0.0.0
      HACKATHON_DB_FILE: /db_data/db.sqlite3
    volumes:
    - hackathon-db-data:/db_data/

  migrator:
    image: hackathon:${HACKATHON_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      HACKATHON_DB_FILE: /db_data/db.sqlite3
    volumes:
    - hackathon-db-data:/db_data/

volumes:
  hackathon-db-data:
    name: hackathon-db-data

networks:
  backend:
    driver: bridge
